### ISSUE TITLE
Java version mismatch

### ISSUE THREAD

**Issue by soundstripe** [koxudaxi/pydantic-pycharm-plugin#164]
**Describe the bug**
When I enable this plugin, it immediately fails, stating that it was compiled with Java version 55.0 and I have Java version 52.0. 

**Stack Trace**

```
com.intellij.diagnostic.PluginException: While loading class com.koxudaxi.pydantic.PydanticTypedValidatorMethodHandler: com/koxudaxi/pydantic/PydanticTypedValidatorMethodHandler has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 [Plugin: com.koxudaxi.pydantic]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:261)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:204)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getImplementationClass(ExtensionComponentAdapter.java:74)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:36)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:69)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:480)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:421)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.calcExtensionList(ExtensionPointImpl.java:248)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:242)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:42)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:16)
	at com.intellij.openapi.application.Preloader.lambda$preload$0(Preloader.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.Preloader.lambda$preload$1(Preloader.java:74)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:183)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:652)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:649)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:649)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedClassVersionError: com/koxudaxi/pydantic/PydanticTypedValidatorMethodHandler has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:423)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:408)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:369)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:258)
	... 33 more
```

**Environments (please complete the following information):**
 - IDE: PyCharm Professional 2020.2 and 2020.1
 - OS: Windows 10
 - Plugin version: 0.1.10 

**Additional context**
I believe PyCharm is configured to use the bundled version of Java provided by JetBrains

**Comment by koxudaxi** [comment]
@soundstripe 
Thank you for reporting this problem.

I don't reproduce the problem in my machine (Windows10 + PyCharm 2020.1 + Plugin version 0.1.10)  :thinking: 

I have checked an official document of Java Runtime. :memo: 
https://www.jetbrains.com/help/pycharm/switching-boot-jdk.html

> As a Java application, PyCharm includes JetBrains Runtime (based on OpenJDK 11), which is used by default. It is recommended to run PyCharm using JetBrains Runtime, which fixes various known OpenJDK and Oracle JDK bugs, and provides better performance and stability. However, in some cases you may be required to use another Java runtime or a specific version of JetBrains Runtime.

PyCharm has Java 11 runtime as default runtime.
Also, You can check and select the runtime with the `Choose Runtime` plugin.
The way is written in the documents.

Pydnatic plugin needs Java 11 runtime.
Would you please check your setting?

## Related links
https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

**Comment by soundstripe** [comment]
After installing "Choose Runtime" I see that the currently selected runtime is:
build 1.8.0_202-release-b1455

It does appear to be a Jetbrains-supplied version (as indicated by the installation path).

Scrolling through the list I selected:
jbsdk11b125_windows_x64.tar.gz

After installing that and re-enabling this plugin it seems to work! Looks like it might be required for your plugin to be on a jbsdk11-based version. Thanks! Hopefully if someone else has the same issue they'll find this answer more quickly now.

**Comment by koxudaxi** [comment]
I'm happy that I can hear a good result :smile: 
Yes, your post can help other people :tada: 
Thank you very much.
