### ISSUE TITLE
Plugin 0.3.8 is not compatible with PyCharm EAP 2021.3

### ISSUE THREAD

**Issue by JrooTJunior** [koxudaxi/pydantic-pycharm-plugin#387]
**Describe the bug**

Latest plugin version is not compatible with most recent EAP version of PyCharm, it can be a big problem when 2021.3 will be released for everyone.

Tested on 0.3.8 plugin version and 0.3.4.

**To Reproduce**
Now this plugin is not compatible with EAP, but can be installed with some changes in `plugin.xml`, so...

1. Set value `until-build="213.*"` in `plugin.xml`
2. Install this plugin from disk
3. Restart IDE
4. See error message

**Expected behavior**
Plugin working without crashing

**Error log**
```java
java.lang.Throwable: 'this constructor' is deprecated and going to be removed soon. 
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:105)
	at com.jetbrains.python.inspections.PyInspectionVisitor.<init>(PyInspectionVisitor.java:52)
	at com.koxudaxi.pydantic.PydanticInspection$Visitor.<init>(PydanticInspection.kt:27)
	at com.koxudaxi.pydantic.PydanticInspection.buildVisitor(PydanticInspection.kt:24)
	at com.intellij.codeInspection.InspectionEngine.createVisitor(InspectionEngine.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.createContext(LocalInspectionsPass.java:474)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:349)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1934)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:349)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:227)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:127)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
**Screenshots**
![image](https://user-images.githubusercontent.com/6726423/138529655-b8fd206c-a9a2-4323-850f-19be9e78194c.png)

**Environments (please complete the following information):**
 - IDE: `PyCharm 2021.3 EAP (Professional Edition) (Build #PY-213.5281.17, built on October 21, 2021)`
 - OS: `Linux 5.14.12-arch1-1 #1 SMP PREEMPT Wed, 13 Oct 2021 16:58:16 +0000 x86_64 GNU/Linux`
 - Pydantic Version: any
 - Plugin version: 0.3.8 and 0.3.4

**Comment by cslominski** [comment]
This exception is now raised on every launch for those auto-updating PyCharm on Ubuntu.

**Comment by koxudaxi** [comment]
@JrooTJunior @chbndrhnns @cslominski 
I'm sorry for my late release.
we can use 0.3.9 on PyCharm 2021.3.*
https://plugins.jetbrains.com/plugin/12861-pydantic/versions/stable/148394

**Comment by Shackelford-Arden** [comment]
Can confirm I no longer see the deprecation message on start up. Thank you @koxudaxi !
