### ISSUE TITLE
Plugin crash in 0.3.10

### ISSUE THREAD

**Issue by LiranKefgg** [koxudaxi/pydantic-pycharm-plugin#424]
my plugin crashes when i open the IDE

> java.lang.NoSuchMethodError: 'com.jetbrains.python.psi.types.TypeEvalContext com.jetbrains.python.inspections.PyInspectionVisitor.getContext(com.intellij.codeInspection.LocalInspectionToolSession)'
	at com.koxudaxi.pydantic.PydanticInspection.buildVisitor(PydanticInspection.kt:25)
	at com.intellij.codeInspection.InspectionEngine.createVisitor(InspectionEngine.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.createContext(LocalInspectionsPass.java:474)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:349)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1934)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:349)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:227)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:127)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Environments (please complete the following information):**
 - IDE: PyCharm Community 20212.2.3
 - OS: win 10
 - Pydantic Version 1.9.0
 - Plugin version 0.3.10

**Comment by koxudaxi** [comment]
@LiranKefgg 

I'm sorry for my late reply.

> IDE: PyCharm Community 20212.2.3

Can you run latest version of PyCharm?
This plugin version supports only 2021.3.x

**Comment by LiranKefgg** [comment]
@koxudaxi  thank you for helping, no need to apologize for helping :)

now the plugin works, thanks
