### ISSUE TITLE
Pycharm 2022.2 exception - java.lang.Throwable: 'this constructor' is deprecated and going to be removed soon. 

### ISSUE THREAD

**Issue by catbreathx** [koxudaxi/pydantic-pycharm-plugin#516]
**Describe the bug**

Opening a project that uses Pydantic, I'm getting the below stack trace consistently and is reported in the IDE Internal Errors dialog

java.lang.Throwable: 'this constructor' is deprecated and going to be removed soon. 
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:105)
	at com.jetbrains.python.inspections.PyInspectionVisitor.<init>(PyInspectionVisitor.java:52)
	at com.koxudaxi.pydantic.PydanticInspection$Visitor.<init>(PydanticInspection.kt:27)
	at com.koxudaxi.pydantic.PydanticInspection.buildVisitor(PydanticInspection.kt:24)
	at com.intellij.codeInspection.InspectionEngine.createVisitor(InspectionEngine.java:66)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.createContext(InspectionRunner.java:351)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$3(InspectionRunner.java:111)
	at com.intellij.util.SmartList.forEach(SmartList.java:349)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$5(InspectionRunner.java:111)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:226)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:109)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:131)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at dcom.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**To Reproduce**
1. Open a project that uses Pydantic package in PyCharm
2. See IDE internal error dialog.

 - IDE: [e.g. PyCharm Pro 2022.2 ]
 - OS: [e.g. macOS  12.4 ]
 - Pydantic Version [e.g. 1.9.0 ]
 - Plugin version [e.g. 0.3.4 ]

**Comment by koxudaxi** [comment]
Thank you for creating the PR.
I think the problem is solved in 0.3.13
