### ISSUE TITLE
PyCharm error reporting

### ISSUE THREAD

**Issue by tonal** [koxudaxi/pydantic-pycharm-plugin#538]
PyCharm 2022.2.1 (Professional Edition)
Current Desktop: KDE
<details><summary>Non-Bundled Plugins:</summary>
<p>

 org.nik.presentation-assistant (1.0.10)
 com.mnr.java.intellij.idea.plugin.base64helper (2.0.3)
 com.intellij.javafx (1.0.4)
 com.intellij.ideolog (203.0.30.0)
 codes.rudolph.idea.cfg (0.3.1)
 cn.jxzhang.plugin.json-formatter (1.4)
    YAML/Ansible support (0.11.2)
    XmlSearchAndReplace2 (0.0.7)
    XPathView (222.3739.16)
    GrepConsole (12.15.211.6693.1)
    org.sonarlint.idea (7.0.0.52289)
    mobi.hsz.idea.gitignore (4.4.2)
    PlantUML integration (5.17.1)
    org.jetbrains.plugins.vue (222.3739.61)
    com.github.jk1.ytplugin (2022.1.212)
    NodeJS (222.3739.16)
    ir.msdehghan.plugins.ansible (0.92)
    ru.meanmail.plugin.requirements (2022.3-222-EAP-SNAPSHOT)
    net.ashald.envfile (3.2.2)
    com.koxudaxi.pydantic (0.3.13)
    com.intellij.bigdatatools (222.3345.33)
    ru.adelf.idea.dotenv (2022.2)
</p>
</details>

```
com.intellij.serviceContainer.AlreadyDisposedException: SDK Python 3.10 (venv) (2): Python 3.10.6 (/home/tonal/projects/FARM-prom/venv/bin/python) (class com.intellij.openapi.projectRoots.impl.ProjectJdkImpl) is already disposed
	at com.jetbrains.python.packaging.PyPackageUtil$4.prepareChange(PyPackageUtil.java:538)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport.lambda$runAsyncListeners$1(AsyncEventSupport.java:90)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:59)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:58)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport.runAsyncListeners(AsyncEventSupport.java:90)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport$1.before(AsyncEventSupport.java:54)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:625)
	at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:470)
	at com.intellij.util.messages.impl.ToDirectChildrenMessagePublisher.publish$intellij_platform_core(CompositeMessageBus.kt:259)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:425)
	at jdk.proxy2/jdk.proxy2.$Proxy168.before(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.fireBeforeEvents(PersistentFSImpl.java:1211)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvent(PersistentFSImpl.java:849)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.deleteFile(PersistentFSImpl.java:561)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.delete(VirtualFileSystemEntry.java:274)
	at com.koxudaxi.pydantic.PydanticPackageManagerListener$packagesRefreshed$lambda-3$$inlined$runWriteAction$1.compute(actions.kt:61)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$13(ApplicationImpl.java:1032)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1011)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1032)
	at com.koxudaxi.pydantic.PydanticPackageManagerListener.packagesRefreshed$lambda-3(PydanticPackageManagerListener.kt:49)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by koxudaxi** [comment]
@tonal 
I'm sorry for my late reply.
The fixed version has been released.
Thank you very much!1
